# Generated by Django 2.2.19 on 2022-09-10 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_auto_20220910_1142'),
        ('api', '0014_auto_20220910_1142'),
        ('admin', '0004_auto_20220910_1142'),
        ('auth', '0011_update_proxy_permissions'),
        ('users', '0007_auto_20220910_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserAccount',
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, to_field='id', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, to_field='id', verbose_name='Пользователь'),
        ),
    ]
