# Generated by Django 2.2.19 on 2022-08-25 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ингридиент')),
                ('measurement_unit', models.CharField(max_length=25, verbose_name='Единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientsAmout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amout', models.FloatField(verbose_name='Количество')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('text', models.TextField(verbose_name='Описание рецепта')),
                ('cooking_time', models.IntegerField(verbose_name='Время приготовления')),
                ('ingridients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingridients', to='recept.Ingredients', verbose_name='Ингридиенты')),
            ],
            options={
                'verbose_name': 'Рецепты',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Тег')),
                ('color', models.CharField(max_length=7, verbose_name='Цветовой HEX-код')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Теги',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='RecipesTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recept.Recipes', verbose_name='Рецепты')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recept.Tags', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Рецепты и теги',
                'verbose_name_plural': 'Рецепты и теги',
            },
        ),
        migrations.AddField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(through='recept.RecipesTags', to='recept.Tags', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='ingridients_amout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isamout', to='recept.IngredientsAmout'),
        ),
    ]
