# Generated by Django 2.2.19 on 2022-08-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0003_auto_20220829_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
