# Generated by Django 2.2.19 on 2022-09-01 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Время приготовления не может быть меньше 0')], verbose_name='Время приготовления'),
        ),
    ]
