# Generated by Django 2.2.19 on 2022-09-05 13:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220901_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amout', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='ingridients_amout',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='ingridients',
        ),
        migrations.DeleteModel(
            name='IngredientsAmout',
        ),
        migrations.AddField(
            model_name='amountingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amout_recipes', to='api.Ingredients', verbose_name='Ингридиент'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingridients',
            field=models.ManyToManyField(related_name='recipes', to='api.AmountIngredients', verbose_name='Ингридиенты'),
        ),
    ]
