# Generated by Django 2.2.19 on 2022-09-05 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220905_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amountingredients',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='amout_recipes', to='api.AmountIngredients', verbose_name='Ингридиент'),
            preserve_default=False,
        ),
    ]
