# Generated by Django 2.2.19 on 2022-09-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220905_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='ingredient',
            new_name='amount',
        ),
    ]
