# Generated by Django 2.2.19 on 2022-09-05 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220905_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountingredients',
            old_name='amout',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_recipes', to='api.AmountIngredients', verbose_name='Ингридиент'),
        ),
    ]
