# Generated by Django 2.2.19 on 2022-09-06 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220905_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountingredients',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Количество не может быть меньше 1.')]),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Время приготовления не может быть меньше 1')], verbose_name='Время приготовления'),
        ),
    ]
