# Generated by Django 2.2.19 on 2022-09-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220906_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountingredients',
            old_name='ingredients',
            new_name='ingredient',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingridients',
            field=models.ManyToManyField(related_name='recipes', to='api.AmountIngredients', verbose_name='Ингридиенты'),
        ),
    ]
